export const ACTION_CONFIG = {
  place_scarecrow: {
    id: "place_scarecrow",
    type: "activate",
    label: "Place scarecrow",
    text: "The scarecrow is secured in the field.",
    i18n: { da: { label: "Placér fugleskræmsel", text: "Fugleskræmslet er sat fast i marken." } },
    requires: { questActive: "place_scarecrows", inventory: { questItemId: "scarecrow", count: 1 } },
    costs: { items: { scarecrow: 1 } },
    addCounters: { farmer_scarecrows_placed: 1 },
    questCounterProgress: {
      questId: "place_scarecrows",
      counter: "farmer_scarecrows_placed",
      progressField: "placed",
      max: 7,
    },
    refreshRegionDecorators: true,
  },
  place_southern_scarecrow: {
    id: "place_southern_scarecrow",
    type: "activate",
    label: "Place scarecrow",
    text: "The new scarecrow is secured in the southern field.",
    i18n: { da: { label: "Placér fugleskræmsel", text: "Det nye fugleskræmsel er sat fast på den sydlige mark." } },
    requires: {
      questStepActive: { questId: "more_scarecrows", stepId: "place_southern_scarecrows" },
      inventory: { questItemId: "scarecrow", count: 1 },
    },
    costs: { items: { scarecrow: 1 } },
    addCounters: { farmer_southern_scarecrows_placed: 1 },
    questCounterProgress: {
      questId: "more_scarecrows",
      stepId: "place_southern_scarecrows",
      counter: "farmer_southern_scarecrows_placed",
      progressField: "placed",
      max: 7,
    },
    refreshRegionDecorators: true,
  },
  inspect_young_boys_body: {
    id: "inspect_young_boys_body",
    type: "inspect",
    label: "Examine the boy",
    text: "The boy is beyond help. In his cold hand is a mud-stained letter, protected all this way for the mother who was still waiting.",
    i18n: { da: { label: "Undersøg drengen", text: "Drengen står ikke til at redde. I hans kolde hånd ligger et mudret brev, beskyttet hele vejen for den mor, der stadig ventede." } },
    requires: {
      all: [
        { questCompleted: "confront_veldor_with_truth" },
        { not: { questCompleted: "the_young_boys_letter" } },
        { notFlag: "young_boys_letter_taken" },
      ],
    },
    rewards: { items: { young_boys_fathers_letter: 1 } },
    questStart: { questId: "the_young_boys_letter", npcId: "grieving_mother" },
    setFlags: ["young_boys_letter_taken"],
    removeTarget: true,
    once: true,
  },

  enter_young_boys_father_cave: {
    id: "enter_young_boys_father_cave",
    type: "enterSubregion",
    label: "Enter the webbed cave",
    i18n: { da: { label: "Gå ind i den spinddækkede grotte" } },
    targetSubregionId: "young_boys_father_cave",
    instanceScope: "sourceObject",
    persistence: "whileRootRegionActive",
    requires: { questStepActive: { questId: "the_young_boys_letter", stepId: "search_fathers_cave" } },
  },

  inspect_young_boys_father: {
    id: "inspect_young_boys_father",
    type: "inspect",
    label: "Examine the father",
    text: "The spiders found him before help could. Beside him lies a final page: he sent his son home with the warning, then stayed to keep the brood inside the cave.",
    i18n: { da: { label: "Undersøg faderen", text: "Edderkopperne fandt ham før hjælpen. Ved hans side ligger en sidste side: Han sendte sin søn hjem med advarslen og blev selv tilbage for at holde ynglen inde i grotten." } },
    readableId: "young_boys_fathers_last_page",
    requires: {
      questStepActive: { questId: "the_young_boys_letter", stepId: "search_fathers_cave" },
      flag: "young_boys_father_cave_cleared",
      notFlag: "young_boys_father_found",
    },
    rewards: { items: { young_boys_fathers_last_page: 1 } },
    setFlags: ["young_boys_father_found"],
    removeTarget: true,
    once: true,
  },
  inspect_random_ruin: {
    id: "inspect_random_ruin",
    type: "inspect",
    label: "Inspect ruin",
    text: "The ruin is ancient and covered in strange markings.",
    i18n: { da: { label: "Undersøg ruin", text: "Ruinen er ældgammel og dækket af mærkelige tegn." } },
    once: false,
  },

  read_demon_notes: {
    id: "read_demon_notes",
    type: "read",
    label: "Read notes",
    i18n: { da: { label: "Læs noter" } },
    readableId: "demon_notes_compiled",
    once: true,
    setFlags: ["read.demon_notes_compiled"],
  },

  collect_sealed_note: {
    id: "collect_sealed_note",
    type: "collect",
    label: "Take note",
    i18n: { da: { label: "Tag note" } },
    rewards: {
      items: { note: 1 },
    },
    removeTarget: true,
    once: true,
    setFlags: ["item.note.collected"],
  },

  collect_merchant_wooden_wheel: {
    id: "collect_merchant_wooden_wheel",
    type: "collect",
    label: "Pick up wooden wheel",
    text: "You recover one of the merchant's scattered wagon wheels.",
    i18n: {
      da: {
        label: "Saml træhjul op",
        text: "Du finder et af handelsmandens spredte vognhjul.",
      },
    },
    requires: { questActive: "merchant_recover_wagon_wheels" },
    rewards: { items: { merchant_wooden_wheel: 1 } },
    removeTarget: true,
    once: true,
  },

  inspect_status_lookout_post: {
    id: "inspect_status_lookout_post",
    type: "inspect",
    label: "Inspect tower",
    text: "The lookout tower is too damaged to serve as a warning post. It must be repaired before it can guard the region again.",
    i18n: { da: { label: "Undersoeg taarn", text: "Udkigstaarnet er for oedelagt til at fungere som varslingspost. Det skal repareres, foer det igen kan beskytte omraadet." } },
    requires: { questActive: "status_on_city_defences", notFlag: "city_defence_status.lookout_post" },
    setFlags: ["city_defence_status.lookout_post"],
    addCounters: { status_on_city_defences_checked: 1 },
    questCounterProgress: { questId: "status_on_city_defences", counter: "status_on_city_defences_checked", progressField: "checked", max: 5 },
    once: true,
  },

  inspect_status_hunter_hut_fence: {
    id: "inspect_status_hunter_hut_fence",
    type: "inspect",
    label: "Inspect fence",
    text: "Three gaps have opened in the fence around the old grave place. The ward is exposed until the fence is repaired.",
    i18n: { da: { label: "Undersoeg hegn", text: "Tre steder er hegnet omkring den gamle gravplads brudt op. Vaernet staar aabent, indtil hegnet bliver repareret." } },
    requires: { questActive: "status_on_city_defences", notFlag: "city_defence_status.hunter_hut_fence" },
    setFlags: ["city_defence_status.hunter_hut_fence"],
    addCounters: { status_on_city_defences_checked: 1 },
    questCounterProgress: { questId: "status_on_city_defences", counter: "status_on_city_defences_checked", progressField: "checked", max: 5 },
    once: true,
  },

  inspect_status_beacon_hunter_trail: {
    id: "inspect_status_beacon_hunter_trail",
    type: "inspect",
    label: "Inspect beacon",
    text: "The beacon is cold. No smoke, no flame, and no warning signal can reach Valtoria from here.",
    i18n: { da: { label: "Undersoeg beacon", text: "Beacon-taarnet er koldt. Ingen roeg, ingen flamme og intet varsel kan naa Valtoria herfra." } },
    requires: { questActive: "status_on_city_defences", notFlag: "city_defence_status.beacon_hunter_trail" },
    setFlags: ["city_defence_status.beacon_hunter_trail"],
    addCounters: { status_on_city_defences_checked: 1 },
    questCounterProgress: { questId: "status_on_city_defences", counter: "status_on_city_defences_checked", progressField: "checked", max: 5 },
    once: true,
  },

  inspect_status_beacon_hunter_hut: {
    id: "inspect_status_beacon_hunter_hut",
    type: "inspect",
    label: "Inspect beacon",
    text: "This beacon has gone out as well. The path is blind unless someone lights it again.",
    i18n: { da: { label: "Undersoeg beacon", text: "Ogsaa dette beacon-taarn er gaaet ud. Stien er blind, indtil nogen taender det igen." } },
    requires: { questActive: "status_on_city_defences", notFlag: "city_defence_status.beacon_hunter_hut" },
    setFlags: ["city_defence_status.beacon_hunter_hut"],
    addCounters: { status_on_city_defences_checked: 1 },
    questCounterProgress: { questId: "status_on_city_defences", counter: "status_on_city_defences_checked", progressField: "checked", max: 5 },
    once: true,
  },

  inspect_status_beacon_inner_elvindale: {
    id: "inspect_status_beacon_inner_elvindale",
    type: "inspect",
    label: "Inspect beacon",
    text: "The last beacon toward the inner valley is dark. If danger moves through Elvindale, the city will not see it coming.",
    i18n: { da: { label: "Undersoeg beacon", text: "Det sidste beacon-taarn mod den indre dal er moerkt. Hvis faren kommer gennem Elvindalen, ser byen det ikke i tide." } },
    requires: { questActive: "status_on_city_defences", notFlag: "city_defence_status.beacon_inner_elvindale" },
    setFlags: ["city_defence_status.beacon_inner_elvindale"],
    addCounters: { status_on_city_defences_checked: 1 },
    questCounterProgress: { questId: "status_on_city_defences", counter: "status_on_city_defences_checked", progressField: "checked", max: 5 },
    once: true,
  },

  repair_destroyed_lookout_tower_west: {
    id: "repair_destroyed_lookout_tower_west",
    type: "repair",
    label: "Repair tower",
    text: "The western ruined tower is rebuilt with fresh timber.",
    i18n: { da: { label: "Reparer taarn", text: "Det vestlige oedelagte taarn bliver genopbygget med friskt trae." } },
    requires: { questActive: "clear_and_repair_the_lookout_post", notFlag: "lookout_post.tower_west_repaired" },
    costs: { resources: { wood_piece: 10 } },
    setFlags: ["lookout_post.tower_west_repaired"],
    replaceTargetWith: "object_watchtowers",
    replaceTargetDestructible: false,
    once: true,
  },

  repair_damaged_lookout_tower_center: {
    id: "repair_damaged_lookout_tower_center",
    type: "repair",
    label: "Repair tower",
    text: "The central damaged tower is braced and made useful again.",
    i18n: { da: { label: "Reparer taarn", text: "Det midterste beskadigede taarn bliver afstivet og gjort brugbart igen." } },
    requires: { questActive: "clear_and_repair_the_lookout_post", notFlag: "lookout_post.tower_center_repaired" },
    costs: { resources: { wood_piece: 5 } },
    setFlags: ["lookout_post.tower_center_repaired"],
    replaceTargetWith: "object_watchtowers",
    replaceTargetDestructible: false,
    once: true,
  },

  repair_destroyed_lookout_tower_east: {
    id: "repair_destroyed_lookout_tower_east",
    type: "repair",
    label: "Repair tower",
    text: "The eastern ruined tower is rebuilt with fresh timber.",
    i18n: { da: { label: "Reparer taarn", text: "Det oestlige oedelagte taarn bliver genopbygget med friskt trae." } },
    requires: { questActive: "clear_and_repair_the_lookout_post", notFlag: "lookout_post.tower_east_repaired" },
    costs: { resources: { wood_piece: 10 } },
    setFlags: ["lookout_post.tower_east_repaired"],
    replaceTargetWith: "object_watchtowers",
    replaceTargetDestructible: false,
    once: true,
  },

  repair_hunter_hut_grave_fence_north: {
    id: "repair_hunter_hut_grave_fence_north",
    type: "repair",
    label: "Repair fence",
    text: "The northern fence gap is repaired with a fresh plank.",
    i18n: { da: { label: "Reparer hegn", text: "Det nordlige hul i hegnet bliver repareret med en frisk planke." } },
    requires: { questActive: "repair_the_fences", notFlag: "hunter_hut_grave_fence.north_repaired" },
    costs: { resources: { wood_plank: 1 } },
    setFlags: ["hunter_hut_grave_fence.north_repaired"],
    replaceTargetWith: "object_pillar_wood",
    replaceTargetDestructible: false,
    once: true,
  },

  repair_hunter_hut_grave_fence_east: {
    id: "repair_hunter_hut_grave_fence_east",
    type: "repair",
    label: "Repair fence",
    text: "The eastern fence gap is repaired with a fresh plank.",
    i18n: { da: { label: "Reparer hegn", text: "Det oestlige hul i hegnet bliver repareret med en frisk planke." } },
    requires: { questActive: "repair_the_fences", notFlag: "hunter_hut_grave_fence.east_repaired" },
    costs: { resources: { wood_plank: 1 } },
    setFlags: ["hunter_hut_grave_fence.east_repaired"],
    replaceTargetWith: "object_pillar_wood",
    replaceTargetDestructible: false,
    once: true,
  },

  repair_hunter_hut_grave_fence_south: {
    id: "repair_hunter_hut_grave_fence_south",
    type: "repair",
    label: "Repair fence",
    text: "The southern fence gap is repaired with a fresh plank.",
    i18n: { da: { label: "Reparer hegn", text: "Det sydlige hul i hegnet bliver repareret med en frisk planke." } },
    requires: { questActive: "repair_the_fences", notFlag: "hunter_hut_grave_fence.south_repaired" },
    costs: { resources: { wood_plank: 1 } },
    setFlags: ["hunter_hut_grave_fence.south_repaired"],
    replaceTargetWith: "object_pillar_wood",
    replaceTargetDestructible: false,
    once: true,
  },

  light_defence_beacon_hunter_trail: {
    id: "light_defence_beacon_hunter_trail",
    type: "activate",
    label: "Light beacon",
    text: "The forest-trail beacon catches. Flame and smoke rise above the path again.",
    i18n: { da: { label: "Taend beacon", text: "Beacon-taarnet ved skovstien faar fat. Flamme og roeg rejser sig igen over stien." } },
    requires: { questActive: "light_the_beacons", notFlag: "defence_beacon.hunter_trail_lit" },
    setFlags: ["defence_beacon.hunter_trail_lit"],
    addCounters: { defence_beacons_lit: 1 },
    questCounterProgress: { questId: "light_the_beacons", counter: "defence_beacons_lit", progressField: "lit", max: 3 },
    replaceTargetWith: "object_firebeacon_normal",
    replaceTargetDestructible: false,
    once: true,
  },

  light_defence_beacon_hunter_hut: {
    id: "light_defence_beacon_hunter_hut",
    type: "activate",
    label: "Light beacon",
    text: "The hunter-hut beacon catches. Flame and smoke rise above the path again.",
    i18n: { da: { label: "Taend beacon", text: "Beacon-taarnet ved jaegerhytten faar fat. Flamme og roeg rejser sig igen over stien." } },
    requires: { questActive: "light_the_beacons", notFlag: "defence_beacon.hunter_hut_lit" },
    setFlags: ["defence_beacon.hunter_hut_lit"],
    addCounters: { defence_beacons_lit: 1 },
    questCounterProgress: { questId: "light_the_beacons", counter: "defence_beacons_lit", progressField: "lit", max: 3 },
    replaceTargetWith: "object_firebeacon_normal",
    replaceTargetDestructible: false,
    once: true,
  },

  light_defence_beacon_inner_elvindale: {
    id: "light_defence_beacon_inner_elvindale",
    type: "activate",
    label: "Light beacon",
    text: "The inner-valley beacon catches. Flame and smoke rise above the path again.",
    i18n: { da: { label: "Taend beacon", text: "Beacon-taarnet mod den indre dal faar fat. Flamme og roeg rejser sig igen over stien." } },
    requires: { questActive: "light_the_beacons", notFlag: "defence_beacon.inner_elvindale_lit" },
    setFlags: ["defence_beacon.inner_elvindale_lit"],
    addCounters: { defence_beacons_lit: 1 },
    questCounterProgress: { questId: "light_the_beacons", counter: "defence_beacons_lit", progressField: "lit", max: 3 },
    replaceTargetWith: "object_firebeacon_normal",
    replaceTargetDestructible: false,
    once: true,
  },

  collect_hunters_love_flower: {
    id: "collect_hunters_love_flower",
    type: "collect",
    label: "Pick the sacred flower",
    text: "The sacred flower comes free without losing a single petal.",
    i18n: {
      da: {
        label: "Pluk den hellige blomst",
        text: "Den hellige blomst slipper jorden uden at miste et eneste kronblad.",
      },
    },
    requires: { questStepActive: { questId: "help_hunter_find_flower", stepId: "find_sacred_flower" } },
    blockedBy: { inventory: { questItemId: "quest_hunters_love_flower", count: 1 } },
    rewards: { items: { quest_hunters_love_flower: 1 } },
    removeTarget: true,
    once: true,
  },

  harvest_rare_pink_flower: {
    id: "harvest_rare_pink_flower",
    type: "harvest",
    label: "Pick flower",
    i18n: { da: { label: "Pluk blomst" } },
    rewards: {
      resources: { rare_pink_flower: 1 },
    },
    removeTarget: true,
    once: true,
  },

  clear_old_barrier: {
    id: "clear_old_barrier",
    type: "destroy",
    label: "Clear barrier",
    i18n: { da: { label: "Ryd barriere" } },
    costs: {
      resources: { wood_piece: 2 },
    },
    removeTarget: true,
    setFlags: ["barrier.old.cleared"],
    once: true,
  },

  open_weathered_chest: {
    id: "open_weathered_chest",
    type: "open",
    label: "Open",
    i18n: { da: { label: "Åbn" } },
    setFlags: ["chest.weathered.opened"],
    once: true,
  },

  open_map_chest: {
    id: "open_map_chest",
    type: "open",
    label: "Open chest",
    i18n: { da: { label: "Åbn kiste" } },
    prompt: "open chest",
    chestLoot: true,
  },

  activate_old_rune: {
    id: "activate_old_rune",
    type: "activate",
    label: "Activate",
    text: "The rune hums briefly, then fades.",
    i18n: { da: { label: "Aktivér", text: "Runen summer kort og falmer derefter." } },
    addCounters: { "rune.old.activations": 1 },
    setFlags: ["rune.old.activated"],
    once: true,
  },

  reveal_small_cache: {
    id: "reveal_small_cache",
    type: "reveal",
    label: "Inspect",
    text: "You find signs of a hidden cache.",
    i18n: { da: { label: "Undersøg", text: "Du finder spor efter et skjult depot." } },
    setFlags: ["cache.small.revealed"],
    once: true,
  },

  cleanse_minor_shrine: {
    id: "cleanse_minor_shrine",
    type: "cleanse",
    label: "Cleanse",
    i18n: { da: { label: "Rens" } },
    costs: {
      resources: { rare_pink_flower: 1 },
    },
    worldEnergy: { lydra: 2, netdra: -1 },
    setFlags: ["shrine.minor.cleansed"],
    once: true,
  },

  repair_old_planks: {
    id: "repair_old_planks",
    type: "repair",
    label: "Repair",
    i18n: { da: { label: "Reparér" } },
    costs: {
      resources: { wood_piece: 2, rock_piece: 1 },
    },
    setFlags: ["planks.old.repaired"],
    once: true,
  },

  repair_village_house: {
    id: "repair_village_house",
    type: "repair",
    label: "Repair house",
    i18n: { da: { label: "Reparér hus" } },
    prompt: "Reparer huset",
    costs: {
      resources: { wood_piece: 2},
    },
    replaceTargetWith: "object_house_mainland",
    replaceTargetDestructible: false,
    once: true,
  },

  repair_smithy_furnace: {
    id: "repair_smithy_furnace",
    type: "repair",
    label: "Repair furnace",
    i18n: { da: { label: "Reparér furnace" } },
    prompt: "Reparer furnace",
    requires: { questActive: "blacksmith_repair_smithy" },
    costs: {
      resources: { iron_plates: 4, iron_chains: 2 },
    },
    replaceTargetWith: "object_furnace",
    replaceTargetDestructible: false,
    once: true,
  },

  repair_smithy_anvil: {
    id: "repair_smithy_anvil",
    type: "repair",
    label: "Repair anvil",
    i18n: { da: { label: "Reparér anvil" } },
    prompt: "Reparer anvil",
    requires: { questActive: "blacksmith_repair_smithy" },
    costs: {
      resources: { iron_plates: 3, iron_chains: 1 },
    },
    replaceTargetWith: "object_anvil",
    replaceTargetDestructible: false,
    once: true,
  },

  repair_smithy_bellow: {
    id: "repair_smithy_bellow",
    type: "repair",
    label: "Repair bellows",
    i18n: { da: { label: "Reparér blæsebælg" } },
    prompt: "Reparer bellow",
    requires: { questActive: "blacksmith_repair_smithy" },
    costs: {
      resources: { iron_plates: 2, iron_chains: 2 },
    },
    replaceTargetWith: "object_bellow",
    replaceTargetDestructible: false,
    once: true,
  },

  inspect_blacksmith_wife: {
    id: "inspect_blacksmith_wife",
    type: "inspect",
    label: "Inspect",
    text: "The woman is dead. The deep bite marks and shattered bones point not to spiders or wolves, but to an enormous boar.",
    i18n: { da: { label: "Undersøg", text: "Kvinden er død. De dybe bidemærker og ødelagte knogler peger ikke på edderkopper eller ulve, men på et enormt vildsvin." } },
    requires: { questActive: "blacksmith_find_wife" },
    once: true,
  },

  bury_village_dead: {
    id: "bury_village_dead",
    type: "cleanse",
    label: "Bury villager",
    i18n: { da: { label: "Begrav landsbyboer" } },
    prompt: "Begrav den doede landsbyboer",
    requires: { questActive: "mayor_repair_village_houses" },    
    replaceFoliageWith: "object/object_gravestone.png",
    replaceFoliageSize: 0.7,
    once: true,
  },

  offer_flower_to_shrine: {
    id: "offer_flower_to_shrine",
    type: "offer",
    label: "Make offering",
    i18n: { da: { label: "Giv offer" } },
    costs: {
      resources: { rare_pink_flower: 1 },
      gold: 10,
    },
    rewards: {
      resources: { magic_essence: 1 },
    },
    setFlags: ["shrine.flower.offered"],
    once: true,
  },

  enter_generic_cave01: {
    id: "enter_generic_cave01",
    type: "enterSubregion",
    label: "Enter",
    i18n: { da: { label: "Gå ind" } },
    targetSubregionId: "cave01_lvl1",
    instanceScope: "sourceObject",
    persistence: "whileRootRegionActive",
  },

  enter_blacksmith_boar_cave_lvl1: {
    id: "enter_blacksmith_boar_cave_lvl1",
    type: "enterSubregion",
    label: "Enter cave",
    i18n: { da: { label: "Gå ind i grotten" } },
    targetSubregionId: "blacksmith_boar_cave_lvl1",
    instanceScope: "sourceObject",
    persistence: "whileRootRegionActive",
    requires: { questActive: "blacksmith_boar_hunt" },
  },

  enter_blacksmith_boar_cave_lvl2: {
    id: "enter_blacksmith_boar_cave_lvl2",
    type: "enterSubregion",
    label: "Go through the crack",
    i18n: { da: { label: "Gå gennem revnen" } },
    targetSubregionId: "blacksmith_boar_cave_lvl2",
    instanceScope: "sourceObject",
    persistence: "whileRootRegionActive",
    requires: { questActive: "blacksmith_boar_hunt" },
  },

  enter_blacksmith_boar_cave_lvl3: {
    id: "enter_blacksmith_boar_cave_lvl3",
    type: "enterSubregion",
    label: "Go deeper",
    i18n: { da: { label: "Gå dybere" } },
    targetSubregionId: "blacksmith_boar_cave_lvl3",
    instanceScope: "sourceObject",
    persistence: "whileRootRegionActive",
    requires: { questActive: "blacksmith_boar_hunt" },
  },

  enter_cave01_lvl2: {
    id: "enter_cave01_lvl2",
    type: "enterSubregion",
    label: "Go deeper",
    i18n: { da: { label: "Gå dybere" } },
    targetSubregionId: "cave01_lvl2",
    instanceScope: "sourceObject",
    persistence: "whileRootRegionActive",
  },

  enter_the_mine_lvl1: {
    id: "enter_the_mine_lvl1",
    type: "enterSubregion",
    label: "Enter the mine",
    i18n: { da: { label: "Gå ned i minen" } },
    targetSubregionId: "the_mine_lvl1",
    instanceScope: "sourceObject",
    persistence: "whileRootRegionActive",
    requires: {
      any: [
        { questActive: "miri_find_father" },
        { flag: "the_mine_unlocked" },
        { questCompleted: "miri_find_father" },
        { questActive: "rusk_gold_nuggets" },
        { questCompleted: "rusk_gold_nuggets" },
        { questActive: "veldor_clear_the_mine" },
        { questCompleted: "veldor_clear_the_mine" },
      ],
    },
    setFlags: ["the_mine_unlocked"],
  },

  enter_the_mine_lvl2: {
    id: "enter_the_mine_lvl2",
    type: "enterSubregion",
    label: "Go deeper",
    i18n: { da: { label: "Gå dybere" } },
    targetSubregionId: "the_mine_lvl2",
    instanceScope: "sourceObject",
    persistence: "whileRootRegionActive",
  },

  enter_the_mine_lvl3: {
    id: "enter_the_mine_lvl3",
    type: "enterSubregion",
    label: "Go deeper",
    i18n: { da: { label: "Gå dybere" } },
    targetSubregionId: "the_mine_lvl3",
    instanceScope: "sourceObject",
    persistence: "whileRootRegionActive",
  },

  enter_forest_mine_lvl1: {
    id: "enter_forest_mine_lvl1",
    type: "enterSubregion",
    label: "Enter the forest mine",
    i18n: { da: { label: "Gå ind i skovminen" } },
    targetSubregionId: "forest_mine_lvl1",
    instanceScope: "sourceObject",
    persistence: "whileRootRegionActive",
    requires: { questActive: "find_veldors_wife" },
  },

  enter_forest_mine_lvl2: {
    id: "enter_forest_mine_lvl2",
    type: "enterSubregion",
    label: "Go deeper",
    i18n: { da: { label: "Gå dybere" } },
    targetSubregionId: "forest_mine_lvl2",
    instanceScope: "sourceObject",
    persistence: "whileRootRegionActive",
  },

  enter_forest_mine_lvl3: {
    id: "enter_forest_mine_lvl3",
    type: "enterSubregion",
    label: "Go deeper",
    i18n: { da: { label: "Gå dybere" } },
    targetSubregionId: "forest_mine_lvl3",
    instanceScope: "sourceObject",
    persistence: "whileRootRegionActive",
  },

  inspect_veldors_wife_corpse: {
    id: "inspect_veldors_wife_corpse",
    type: "inspect",
    label: "Inspect the body",
    text: "The dead woman wears Veldor's seal on a broken chain. The letter supplied the name, and here lies the truth: Veldor's wife was abandoned in the mine.",
    i18n: { da: { label: "Undersøg liget", text: "Den døde kvinde bærer Veldors segl i en bristet kæde. Brevet gav navnet, og her ligger sandheden: Veldors kone blev efterladt i minen." } },
    requires: { questActive: "find_veldors_wife", notFlag: "veldors_wife_found" },
    setFlags: ["veldors_wife_found"],
    removeTarget: true,
    once: true,
  },

  exit_subregion: {
    id: "exit_subregion",
    type: "exitSubregion",
    label: "Go back",
  i18n: { da: { label: "Gå tilbage" } },
  i18n: { da: { label: "Gå tilbage" } },
  i18n: { da: { label: "Gå tilbage" } },
  },

  inspect_inn_crack: {
    id: "inspect_inn_crack",
    type: "inspect",
    label: "Inspect the crack",
    text: "The crack is fresh, and webs lead down into the darkness beneath the inn.",
    i18n: { da: { label: "Undersøg revnen", text: "Revnen er frisk, og spind trækker ned i mørket under kroen." } },
    requires: {
      questStepActive: { questId: "check_inn_infestation", stepId: "inspect_cellar" },
      notFlag: "inn_crack_found",
    },
    blockedBy: {
      flag: "inn_crack_destroyed",
    },
    setFlags: ["inn_crack_found"],
  },

  enter_inn_crack_cave: {
    id: "enter_inn_crack_cave",
    type: "enterSubregion",
    label: "Climb down through the crack",
    i18n: { da: { label: "Gå ned gennem revnen" } },
    targetSubregionId: "inn_crack_cave",
    instanceScope: "sourceObject",
    persistence: "whileRootRegionActive",
    requires: {
      any: [
        { questStepActive: { questId: "check_inn_infestation", stepId: "enter_crack" } },
        { questStepActive: { questId: "check_inn_infestation", stepId: "clear_crack_cave" } },
      ],
      notFlag: "inn_crack_cave_cleared",
    },
    setFlags: ["inn_crack_entered"],
  },

  destroy_inn_crack: {
    id: "destroy_inn_crack",
    type: "destroy",
    label: "Destroy the crack",
    i18n: { da: { label: "Ødelæg revnen" } },
    prompt: "Oedelaeg revnen",
    requires: {
      questStepCompleted: { questId: "check_inn_infestation", stepId: "clear_crack_cave" },
      notFlag: "inn_crack_destroyed",
    },
    setFlags: ["inn_crack_destroyed"],
    removeTarget: true,
    questAdvance: {
      questId: "check_inn_infestation",
      stepId: "seal_crack",
    },
    once: true,
  },

  talk_test_wanderer: {
    id: "talk_test_wanderer",
    type: "talk",
    label: "Talk",
    text: "The stranger nods and says: 'Take care in the dark.'",
    i18n: { da: { label: "Tal", text: "Den fremmede nikker og siger: 'Pas på i mørket.'" } },
    once: true,
  },

  talk_lost_miner: {
    id: "talk_lost_miner",
    type: "talk",
    label: "Talk",
    text: "The miner holds the lamp close. 'There is something farther inside.'",
    i18n: { da: { label: "Tal", text: "Minearbejderen holder lampen tæt ind til kroppen. 'Der er noget længere inde.'" } },
    once: false,
  },

  summon_wolf_boss: {
    id: "summon_wolf_boss",
    type: "summon",
    allowStub: true,
    label: "Summon",
    i18n: { da: { label: "Tilkald" } },
    spawn: [{ monsterId: "wolf_boss", count: 1 }],
    setFlags: ["summoned.wolf_boss"],
    once: true,
  },

  start_lost_note_quest: {
    id: "start_lost_note_quest",
    type: "questStart",
    allowStub: true,
    label: "Accept quest",
    i18n: { da: { label: "Tag imod opgave" } },
    questId: "lost_note",
    once: true,
  },

  deliver_ring_to_noble: {
    id: "deliver_ring_to_noble",
    type: "questAdvance",
    allowStub: true,
    label: "Deliver ring",
    i18n: { da: { label: "Aflever ring" } },
    questId: "noble_ring",
    stepId: "deliver_ring",
    costs: {
      items: { ring: 1 },
    },
    rewards: {
      items: { unsigned_document: 1 },
    },
    setFlags: ["noble.received_ring"],
    once: true,
  },
  collect_villager_haystack: {
    id: "collect_villager_haystack",
    type: "collect",
    label: "Collect hay",
    prompt: "Collect haystack",
    requires: {
      questActive: "villager_help_collect_hay",
    },
    rewards: {
      items: {
        villager_haystack: 1,
      },
    },
    removeTarget: true,
    once: true,
    i18n: {
      da: {
        label: "Saml hø",
        prompt: "Saml høstak",
      },
    },
  },
  bury_city_mob_dead: {
    id: "bury_city_mob_dead",
    type: "cleanse",
    label: "Bury villager",
    i18n: {
      da: {
        label: "Begrav landsbyboer",
      },
    },
    prompt: "Begrav den døde landsbyboer",
    worldEnergy: {
      lydra: 0.1,
    },
    replaceFoliageWith: "object/object_gravestone.png",
    replaceFoliageSize: 0.7,
    targetStateScope: "runtime",
    once: false,
  },
};
