export const MUSIC_TRACKS = Object.freeze({
  last_stand_of_valtoria_01: { file: "/audio/music/menu/last_stand_of_valtoria_01.mp3", bus: "music", volume: 0.7, loop: true },
  forest_exploration_01: { file: "/audio/music/forest_exploration_01.mp3", bus: "music", volume: 0.7, loop: true },
  city_threat_low_01: { files: ["/audio/music/city/city_threat_low_01.mp3", "/audio/music/city/city_threat_low_02.mp3", "/audio/music/city/city_threat_low_03.mp3", "/audio/music/city/city_threat_low_04.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  city_threat_high_01: { files: ["/audio/music/city/city_threat_high_01.mp3", "/audio/music/city/city_threat_high_02.mp3", "/audio/music/city/city_threat_high_03.mp3", "/audio/music/city/city_threat_high_04.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  city_threat_very_high_01: { files: ["/audio/music/city/city_threat_very_high_01.mp3", "/audio/music/city/city_threat_very_high_02.mp3", "/audio/music/city/city_threat_very_high_03.mp3", "/audio/music/city/city_threat_very_high_04.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  environment_forest: { files: ["/audio/music/forest_exploration_01.mp3", "/audio/music/environment/Maybe Hope In The Forest.mp3", "/audio/music/environment/Spring is Here.mp3", "/audio/music/environment/Hope Rising.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  environment_forest_dark: { files: ["/audio/music/environment/Dark But Not.mp3", "/audio/music/environment/Darkness Is Close.mp3", "/audio/music/environment/Maybe Hope In The Forest.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  environment_mainland_paths: { files: ["/audio/music/environment/Thinkning is All.mp3", "/audio/music/environment/Maybe Hope In The Forest.mp3", "/audio/music/environment/All is Well.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  environment_fields: { files: ["/audio/music/environment/Summer is Good.mp3", "/audio/music/environment/Spring is Here.mp3", "/audio/music/environment/All is Well.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  environment_village: { files: ["/audio/music/environment/All is Well.mp3", "/audio/music/environment/Happy Times.mp3", "/audio/music/environment/Violin Dancing.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  environment_village_lively: { files: ["/audio/music/environment/Violin Dancing.mp3", "/audio/music/environment/Dancing Swing.mp3", "/audio/music/environment/Happy Times.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  environment_village_troubled: { files: ["/audio/music/environment/What that Feeling.mp3", "/audio/music/environment/Dark But Not.mp3", "/audio/music/environment/Tension Rising.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  environment_riverlands: { files: ["/audio/music/environment/Hope Rising.mp3", "/audio/music/environment/Spring is Here.mp3", "/audio/music/environment/Thinkning is All.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  environment_ancient_shrine: { files: ["/audio/music/environment/What that Feeling.mp3", "/audio/music/environment/Dark But Not.mp3", "/audio/music/environment/Thinkning is All.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  environment_ruined_outpost: { files: ["/audio/music/environment/Darkness Is Close.mp3", "/audio/music/environment/Tension Rising.mp3", "/audio/music/environment/Dark But Not.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  environment_cellar: { files: ["/audio/music/environment/Dark Dungeon.mp3", "/audio/music/environment/Dungeon Down.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  environment_deep_dungeon: { files: ["/audio/music/environment/Deep Dungeon.mp3", "/audio/music/environment/Dungeon Deep Down.mp3", "/audio/music/environment/Dungeon Down.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  environment_dungeon_danger: { files: ["/audio/music/environment/Hell is Loose.mp3", "/audio/music/environment/Darkness Is Close.mp3", "/audio/music/environment/Tension Rising.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
  environment_rocky_highlands: { files: ["/audio/music/environment/Tension Rising.mp3", "/audio/music/environment/Dark But Not.mp3", "/audio/music/environment/Thinkning is All.mp3"], bus: "music", volume: 0.7, loop: true, rotateVariants: true },
});

export const MUSIC_PROFILES = Object.freeze({
  menu: Object.freeze({ trackId: "last_stand_of_valtoria_01", fadeMs: 1400 }),
  forest: Object.freeze({ trackId: "environment_forest", fadeMs: 1400 }),
  forest_dark: Object.freeze({ trackId: "environment_forest_dark", fadeMs: 1400 }),
  mainland_paths: Object.freeze({ trackId: "environment_mainland_paths", fadeMs: 1400 }),
  fields: Object.freeze({ trackId: "environment_fields", fadeMs: 1400 }),
  village: Object.freeze({ trackId: "environment_village", fadeMs: 1400 }),
  village_lively: Object.freeze({ trackId: "environment_village_lively", fadeMs: 1400 }),
  village_troubled: Object.freeze({ trackId: "environment_village_troubled", fadeMs: 1400 }),
  riverlands: Object.freeze({ trackId: "environment_riverlands", fadeMs: 1400 }),
  ancient_shrine: Object.freeze({ trackId: "environment_ancient_shrine", fadeMs: 1400 }),
  ruined_outpost: Object.freeze({ trackId: "environment_ruined_outpost", fadeMs: 1400 }),
  cellar: Object.freeze({ trackId: "environment_cellar", fadeMs: 1400 }),
  deep_dungeon: Object.freeze({ trackId: "environment_deep_dungeon", fadeMs: 1400 }),
  dungeon_danger: Object.freeze({ trackId: "environment_dungeon_danger", fadeMs: 1400 }),
  rocky_highlands: Object.freeze({ trackId: "environment_rocky_highlands", fadeMs: 1400 }),
  city_low_threat: Object.freeze({ trackId: "city_threat_low_01", fadeMs: 1400 }),
  city_high_threat: Object.freeze({ trackId: "city_threat_high_01", fadeMs: 1400 }),
  city_very_high_threat: Object.freeze({ trackId: "city_threat_very_high_01", fadeMs: 1400 }),
});
