export const QUEST_NPCS = {
  mayor: {
    name: "Mayor",
    title: "Mayor",
    i18n: { da: { title: "Borgmester" } },
    imageUrl: "/assets/generated/npc/npc_mayor.png",
    cityLocation: "town_center",
    cityHint: "Ved byens midte",
    wildernessText: "Byens borgmester holder sig normalt ved byens midte, hvor han tager imod nye ankomne.",
    dialogue: {
      active: "Tal med innkeeper. Byen har brug for at se, at du vil hjaelpe.",
      completed: "Godt. Hjaelp byens folk, saa vender haabet langsomt tilbage.",
    },
  },
  blacksmith: {
    name: "Traver",
    title: "Blacksmith",
    i18n: { da: { title: "Smed" } },
    imageUrl: "/assets/generated/npc/npc_blacksmith.png",
    cityLocation: "blacksmith",
    cityHint: "Ved blacksmith i byen",
    wildernessText: "Traver leder efter spor i vildmarken, fordi nogen har rodet i smedjens vigtigste vaerktoejer.",
  },
  farmer: {
    name: "Willis",
    title: "Farmer",
    i18n: { da: { title: "Bonde" } },
    imageUrl: "/assets/generated/npc/npc_farmer.png",
    cityLocation: "farm",
    cityHint: "Ved farmen i byen",
    wildernessText: "Willis gaar uden for markerne for at finde ud af, hvad der driver baesterne taettere paa byen.",
  },
  hunter: {
    name: "Y'atho",
    title: "Hunter",
    i18n: { da: { title: "Jaeger" } },
    imageUrl: "/assets/generated/npc/npc_hunter.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "Y'atho rejser efter friske spor og dukker op, naar jagten har brug for en haand mere.",
  },
  innkeeper: {
    name: "Oliver",
    title: "Innkeeper",
    i18n: { da: { title: "Krovaert" } },
    imageUrl: "/assets/generated/npc/npc_innkeeper.png",
    cityLocation: "inn",
    cityHint: "Ved inn i byen",
    wildernessText: "Oliver samler rygter fra rejsende, men nogle historier kraever handling uden for bymuren.",
  },
  mage: {
    name: "Darium",
    title: "Mage",
    i18n: { da: { title: "Magiker" } },
    imageUrl: "/assets/generated/npc/npc_mage.png",
    cityLocation: "mage_tower",
    cityHint: "Ved mage tower i byen",
    wildernessText: "Darium foelger runeuroen ud i vildmarken, naar magien begynder at traekke i forkerte retninger.",
  },
  merchant: {
    name: "Elis",
    title: "Merchant",
    i18n: { da: { title: "Koebmand" } },
    imageUrl: "/assets/generated/npc/npc_merchant.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "Elis leder efter tabte varer, farlige ruter og nye grunde til at betale nogen for besvaeret.",
  },
  noble: {
    name: "Turanios",
    title: "Noble",
    i18n: { da: { title: "Adelig" } },
    imageUrl: "/assets/generated/npc/npc_noble.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "Turanios rejser med for mange fine ting og for lidt respekt for farerne uden for vejene.",
  },
  soldier: {
    name: "Himus",
    title: "Soldier",
    i18n: { da: { title: "Soldat" } },
    imageUrl: "/assets/generated/npc/npc_soldier.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "Himus tjener en ukendt haer og holder oeje med trusler, der endnu ikke har naaet byporten.",
  },
  wiseman: {
    name: "Vitlias",
    title: "Wiseman",
    i18n: { da: { title: "Vismand" } },
    imageUrl: "/assets/generated/npc/npc_wiseman.png",
    cityLocation: "library",
    cityHint: "Ved library i byen",
    wildernessText: "Vitlias soeger gamle tegn i landskabet og sender andre efter det, hans knogler ikke laengere kan naa.",
  },
  captain: {
    name: "Kaptajn Varlo",
    title: "Captain",
    i18n: { da: { title: "Kaptajn" } },
    imageUrl: "/assets/generated/npc/npc_captain.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "Kaptajn Varlo leder efter vragrester og en rute mod Tornvalhed.",
  },
  begger: {
    name: "Tigger",
    title: "Beggar",
    i18n: { da: { title: "Tigger" } },
    imageUrl: "/assets/generated/npc/npc_begger.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En tigger, som gaar rundt og leder efter smaatinger og rygter i omegnen.",
  },
  cook: {
    name: "Marla",
    title: "Cook",
    i18n: { da: { title: "Kok" } },
    imageUrl: "/assets/generated/npc/npc_cook.png",
    cityLocation: "inn",
    cityHint: "Ved inn i byen",
    wildernessText: "Marla er byens kok og sender dig ofte ud for at finde specielle ingredienser.",
  },
  creature: {
    name: "O'la-chan",
    title: "Creature",
    i18n: { da: { title: "Skabning" } },
    imageUrl: "/assets/generated/npc/npc_creature.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En underlig skabning, der virker malplaceret i byen og har set ting i vildmarken.",
  },
  lady: {
    name: "Annelise",
    title: "Lady",
    i18n: { da: { title: "Dame" } },
    imageUrl: "/assets/generated/npc/npc_lady.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En velklaedt kvinde paa jagt efter noget tabt eller en tjeneste i det fjerne.",
  },
  oneleggedman: {
    name: "Enben",
    title: "Onelegged Man",
    i18n: { da: { title: "Enbenet mand" } },
    imageUrl: "/assets/generated/npc/npc_oneleggedman.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En mand med et enben, der snakker om havet og gamle smaa eventyr.",
  },
  poorboy: {
    name: "Jory",
    title: "Poor Boy",
    i18n: { da: { title: "Fattig dreng" } },
    imageUrl: "/assets/generated/npc/npc_poorboy.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En ung dreng, som ofte soeger arbejde eller lidt mad uden for byen.",
  },
  sailor: {
    name: "Svend",
    title: "Sailor",
    i18n: { da: { title: "Soemand" } },
    imageUrl: "/assets/generated/npc/npc_sailor.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En soemand som deler historier om fjerne hav og vragrester langs kysten.",
  },
  darkwizard: {
    name: "Morthen",
    title: "Dark Wizard",
    i18n: { da: { title: "Mork troldmand" } },
    imageUrl: "/assets/generated/npc/npc_darkwizard.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En dunkel troldmand med kendskab til forbudte ritualer.",
  },
  dwarf: {
    name: "Brom",
    title: "Dwarf",
    i18n: { da: { title: "Dvaerg" } },
    imageUrl: "/assets/generated/npc/npc_dwarf.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En stenhaard dvarg, der kan laese klippespor som andre laeser bogstaver.",
  },
  eldiria: {
    name: "Eldiria",
    title: "High Seer",
    i18n: { da: { title: "Hojseer" } },
    imageUrl: "/assets/generated/npc/npc_eldiria.png",
    citySpawn: false,
    cityLocation: "random",
    cityHint: "Uden for byen",
    wildernessText: "Eldiria viser sig kun i vildmarken, naar gamle tegn vaekkes til live.",
  },
  elver: {
    name: "Caelen",
    title: "Elf",
    i18n: { da: { title: "Elver" } },
    imageUrl: "/assets/generated/npc/npc_elver.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En vaagen elver, der holder oeje med stierne mellem skov og by.",
  },
  elvera: {
    name: "Elvera",
    title: "Elf",
    i18n: { da: { title: "Skovvogter" } },
    imageUrl: "/assets/generated/npc/npc_elvera.png",
    citySpawn: false,
    cityLocation: "random",
    cityHint: "Uden for byen",
    wildernessText: "Elvera bevogter naturens graenser og traeder kun frem i vildmarken.",
  },
  farmer2: {
    name: "Bertil",
    title: "Farmer",
    i18n: { da: { title: "Bonde" } },
    imageUrl: "/assets/generated/npc/npc_farmer2.png",
    cityLocation: "farm",
    cityHint: "Ved farmen i byen",
    wildernessText: "En ekstra haand fra markerne, som kender terranet uden for byen.",
  },
  foldrik: {
    name: "Foldrik",
    title: "Pathfinder",
    i18n: { da: { title: "Spejder" } },
    imageUrl: "/assets/generated/npc/npc_foldrik.png",
    citySpawn: false,
    cityLocation: "random",
    cityHint: "Uden for byen",
    wildernessText: "Foldrik leder efter sikre ruter, hvor de fleste kun ser fare.",
  },
  ghost: {
    name: "Whisper",
    title: "Ghost",
    i18n: { da: { title: "Spogelse" } },
    imageUrl: "/assets/generated/npc/npc_ghost.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "Et rastloest spogelse med minder om steder, ingen laengere gaar hen.",
  },
  goat: {
    name: "Goat",
    title: "Mountain Goat",
    i18n: { da: { title: "Bjergged" } },
    imageUrl: "/assets/generated/npc/npc_goat.png",
    citySpawn: false,
    cityLocation: "random",
    cityHint: "Uden for byen",
    wildernessText: "Et sejlivede bjergged, der kun findes i vildmarkens stejle kanter.",
  },
  king: {
    name: "Aureon",
    title: "King",
    i18n: { da: { title: "Konge" } },
    imageUrl: "/assets/generated/npc/npc_king.png",
    cityLocation: "town_center",
    cityHint: "Ved byens midte",
    wildernessText: "En konge paa rejse, der soeger sandheden bag Valtorias fald.",
  },
  ladylirian: {
    name: "Lady Lirian",
    title: "Lady",
    i18n: { da: { title: "Dame" } },
    imageUrl: "/assets/generated/npc/npc_ladylirian.png",
    citySpawn: false,
    cityLocation: "random",
    cityHint: "Uden for byen",
    wildernessText: "Lady Lirian dukker op ved ruinmarker, hvor historien stadig hvisker.",
  },
  lordkealand: {
    name: "Lord Kealand",
    title: "Lord",
    i18n: { da: { title: "Lord" } },
    imageUrl: "/assets/generated/npc/npc_lordkealand.png",
    citySpawn: false,
    cityLocation: "random",
    cityHint: "Uden for byen",
    wildernessText: "Lord Kealand rejser med fae sparte ord og mange skjulte planer.",
  },
  lydrendor: {
    name: "Lydrendor",
    title: "Elven King",
    i18n: { da: { title: "Elverkonge" } },
    imageUrl: "/assets/generated/npc/npc_lydrendor.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "Den gamle elverkonge bærer svar, men deler dem kun med de vedholdende.",
  },
  nethrendor: {
    name: "Nethrendor",
    title: "Shadow Lord",
    i18n: { da: { title: "Skyggehersker" } },
    imageUrl: "/assets/generated/npc/npc_nethrendor.png",
    citySpawn: false,
    cityLocation: "random",
    cityHint: "Uden for byen",
    wildernessText: "Nethrendors skygge maerkes i vildmarken, laenge foer han selv ses.",
  },
  poorgirl: {
    name: "Miri",
    title: "Poor Girl",
    i18n: { da: { title: "Fattig pige" } },
    imageUrl: "/assets/generated/npc/npc_poorgirl.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En pige paa jagt efter forsyninger, foer natten falder paa.",
  },
  poorminer: {
    name: "Rusk",
    title: "Poor Miner",
    i18n: { da: { title: "Fattig minearbejder" } },
    imageUrl: "/assets/generated/npc/npc_poorminer.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En slidt minearbejder, der kender gamle skakter under jorden.",
  },
  priest: {
    name: "Iolan",
    title: "Priest",
    i18n: { da: { title: "Praest" } },
    imageUrl: "/assets/generated/npc/npc_priest.png",
    cityLocation: "library",
    cityHint: "Ved library i byen",
    wildernessText: "En praest, der samler relikvier og boenner i de glemte egne.",
  },
  richman: {
    name: "Veldor",
    title: "Rich Man",
    i18n: { da: { title: "Rig mand" } },
    imageUrl: "/assets/generated/npc/npc_richman.png",
    cityLocation: "town_center",
    cityHint: "Ved byens midte",
    wildernessText: "En velhavende samler af sjaeldne ting med dyre vaner og dyrere hemmeligheder.",
  },
  spy: {
    name: "Shade",
    title: "Spy",
    i18n: { da: { title: "Spion" } },
    imageUrl: "/assets/generated/npc/npc_spy.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En skygge mellem lejre og ruiner, altid et skridt foran rygtet.",
  },
};
