export const QUEST_NPCS = {
  mayor: {
    name: "Mayor",
    title: "Mayor",
    imageUrl: "/assets/generated/npc/npc_mayor.png",
    cityLocation: "town_center",
    cityHint: "Ved byens midte",
    wildernessText: "Byens borgmester holder sig normalt ved byens midte, hvor han tager imod nye ankomne.",
    dialogue: {
      active: "Tal med innkeeper. Byen har brug for at se, at du vil hjaelpe.",
      completed: "Godt. Hjaelp byens folk, saa vender haabet langsomt tilbage.",
    },
  },
  blacksmith: {
    name: "Traver",
    title: "Blacksmith",
    imageUrl: "/assets/generated/npc/npc_blacksmith.png",
    cityLocation: "blacksmith",
    cityHint: "Ved blacksmith i byen",
    wildernessText: "Traver leder efter spor i vildmarken, fordi nogen har rodet i smedjens vigtigste vaerktoejer.",
  },
  farmer: {
    name: "Willis",
    title: "Farmer",
    imageUrl: "/assets/generated/npc/npc_farmer.png",
    cityLocation: "farm",
    cityHint: "Ved farmen i byen",
    wildernessText: "Willis gaar uden for markerne for at finde ud af, hvad der driver baesterne taettere paa byen.",
  },
  hunter: {
    name: "Y'atho",
    title: "Hunter",
    imageUrl: "/assets/generated/npc/npc_hunter.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "Y'atho rejser efter friske spor og dukker op, naar jagten har brug for en haand mere.",
  },
  innkeeper: {
    name: "Oliver",
    title: "Innkeeper",
    imageUrl: "/assets/generated/npc/npc_innkeeper.png",
    cityLocation: "inn",
    cityHint: "Ved inn i byen",
    wildernessText: "Oliver samler rygter fra rejsende, men nogle historier kraever handling uden for bymuren.",
  },
  mage: {
    name: "Darium",
    title: "Mage",
    imageUrl: "/assets/generated/npc/npc_mage.png",
    cityLocation: "mage_tower",
    cityHint: "Ved mage tower i byen",
    wildernessText: "Darium foelger runeuroen ud i vildmarken, naar magien begynder at traekke i forkerte retninger.",
  },
  merchant: {
    name: "Elis",
    title: "Merchant",
    imageUrl: "/assets/generated/npc/npc_merchant.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "Elis leder efter tabte varer, farlige ruter og nye grunde til at betale nogen for besvaeret.",
  },
  noble: {
    name: "Turanios",
    title: "Noble",
    imageUrl: "/assets/generated/npc/npc_noble.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "Turanios rejser med for mange fine ting og for lidt respekt for farerne uden for vejene.",
  },
  soldier: {
    name: "Himus",
    title: "Soldier",
    imageUrl: "/assets/generated/npc/npc_soldier.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "Himus tjener en ukendt haer og holder oeje med trusler, der endnu ikke har naaet byporten.",
  },
  wiseman: {
    name: "Vitlias",
    title: "Wiseman",
    imageUrl: "/assets/generated/npc/npc_wiseman.png",
    cityLocation: "library",
    cityHint: "Ved library i byen",
    wildernessText: "Vitlias soeger gamle tegn i landskabet og sender andre efter det, hans knogler ikke laengere kan naa.",
  },
  captain: {
    name: "Kaptajn Varlo",
    title: "Captain",
    imageUrl: "/assets/generated/npc/npc_captain.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "Kaptajn Varlo leder efter vragrester og en rute mod Tornvalhed.",
  },
  begger: {
    name: "Tigger",
    title: "Begger",
    imageUrl: "/assets/generated/npc/npc_begger.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En tigger, som gaar rundt og leder efter smaatinger og rygter i omegnen.",
  },
  cook: {
    name: "Marla",
    title: "Cook",
    imageUrl: "/assets/generated/npc/npc_cook.png",
    cityLocation: "inn",
    cityHint: "Ved inn i byen",
    wildernessText: "Marla er byens kok og sender dig ofte ud for at finde specielle ingredienser.",
  },
  creature: {
    name: "O'la-chan",
    title: "Creature",
    imageUrl: "/assets/generated/npc/npc_creature.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En underlig skabning, der virker malplaceret i byen og har set ting i vildmarken.",
  },
  lady: {
    name: "Annelise",
    title: "Lady",
    imageUrl: "/assets/generated/npc/npc_lady.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En velklaedt kvinde paa jagt efter noget tabt eller en tjeneste i det fjerne.",
  },
  oneleggedman: {
    name: "Enben",
    title: "Onelegged Man",
    imageUrl: "/assets/generated/npc/npc_oneleggedman.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En mand med et enben, der snakker om havet og gamle smaa eventyr.",
  },
  poorboy: {
    name: "Jory",
    title: "Poor Boy",
    imageUrl: "/assets/generated/npc/npc_poorboy.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En ung dreng, som ofte soeger arbejde eller lidt mad uden for byen.",
  },
  sailor: {
    name: "Svend",
    title: "Sailor",
    imageUrl: "/assets/generated/npc/npc_sailor.png",
    cityLocation: "random",
    cityHint: "Et aabent sted i byen",
    wildernessText: "En soemand som deler historier om fjerne hav og vragrester langs kysten.",
  },
};
