export const PERFORMANCE_PROFILES = {
  quality: {
    id: "quality",
    label: "Quality",
    targetFps: 60,
    ambientRenderFps: 15,
    maxDpr: 1.5,
    fogRenderScale: 0.5,
    particleQuality: "high",
    maxParticles: 900,
    disableAmbientCritters: false,
    lowPowerMode: false,
  },
  testing: {
    id: "testing",
    label: "Testing",
    targetFps: 60,
    ambientRenderFps: 12,
    maxDpr: 1,
    fogRenderScale: 0.4,
    particleQuality: "medium",
    maxParticles: 650,
    disableAmbientCritters: false,
    lowPowerMode: false,
  },
  balanced: {
    id: "balanced",
    label: "Balanced",
    targetFps: 50,
    ambientRenderFps: 12,
    maxDpr: 1.25,
    fogRenderScale: 0.45,
    particleQuality: "medium",
    maxParticles: 650,
    disableAmbientCritters: false,
    lowPowerMode: false,
  },
  cool: {
    id: "cool",
    label: "Cool",
    targetFps: 40,
    ambientRenderFps: 10,
    maxDpr: 1,
    fogRenderScale: 0.35,
    particleQuality: "low",
    maxParticles: 420,
    disableAmbientCritters: false,
    lowPowerMode: true,
  },
  silent: {
    id: "silent",
    label: "Silent",
    targetFps: 30,
    ambientRenderFps: 8,
    maxDpr: 1,
    fogRenderScale: 0.3,
    particleQuality: "low",
    maxParticles: 250,
    disableAmbientCritters: true,
    lowPowerMode: true,
  },
};

export const AMBIENT_CRITTER_DEFAULTS = {
  enabled: true,
  maxAlivePerRegion: 20,
  maxPerType: 10,
  collision: false,
  hostile: false,
  canBeTargeted: false,
  givesXp: false,
  dropsLoot: false,
  persist: false,
  offscreenUpdate: false,
  offscreenRender: false,
};

export function resolvePerformanceProfile(mode = "balanced") {
  const key = String(mode ?? "balanced").trim().toLowerCase();
  return PERFORMANCE_PROFILES[key] ?? PERFORMANCE_PROFILES.balanced;
}
