/*
Spell world energy notes:
- netdra / lydra on a spell are consequences when the player casts the spell, not mana costs.
- Values are raw world energy points and can be decimals.
- Example: netdra: 2 adds 2 Net'dra'thot every time the spell is cast.
- Leave both fields out, or set them to 0, for spells that should not affect world energy.
*/
export const SPELL_DEFS = {
  ember_spark: {
    id: "ember_spark",
    title: "Ember Spark",
    starter: true,
    manaCost: 14,
    cooldown: 1.2,
    range: 5.2,
    speed: 8.4,
    element: "arcane",
    hitDamage: 7,
    magicScale: 0.75,
    hitMagicScale: 0.75,
    areaMagicScale: 0.25,
    areaDamage: 5,
    areaRadius: 0.85,
    color: "#9de9ff",
    visuals: {
      castEffect: "cast_arcane",
      projectileEffect: "trail_arcane",
      impactEffect: "impact_arcane",
      projectileTexture: "/assets/generated/particles/arcane_orb.png",
      projectileTextureSize: 32,
    },
    particles: {
      trail: {
        type: "trail_arcane",
        texture: "/assets/generated/particles/arcane_orb.png",
        size: [8, 15],
        endSize: [2, 6],
        alpha: [0.18, 0.42],
        lifetime: [0.18, 0.42],
        spawnRate: 18,
      },
    },
  },
  fireball: {
    id: "fireball",
    title: "Fire Ball",
    manaCost: 16,
    cooldown: 1.25,
    range: 6,
    speed: 8.8,
    element: "fire",
    hitDamage: 12,
    magicScale: 1.15,
    hitMagicScale: 1.15,
    dotMagicScale: 0.12,
    dotDamage: 4,
    dotDuration: 3,
    areaRadius: 0.55,
    color: "#ff7b38",
    visuals: {
      castEffect: "cast_fire",
      projectileEffect: "trail_fire",
      impactEffect: "fire_blast",
      statusEffect: "status_burning",
      projectileTexture: "/assets/generated/particles/fireball_trail.png",
      projectileTextureSize: 42,
      rotateProjectileTexture: true,
      projectileTextureRotationOffset: -2.35619449,
    },
    particles: {
      trail: {
        type: "trail_fire",
        size: [2, 5],
        endSize: [1, 2],
        alpha: [0.12, 0.28],
        lifetime: [0.14, 0.32],
        spawnRate: 12,
      },
    },
  },
  explosion: {
    id: "explosion",
    title: "Explosion",
    manaCost: 22,
    cooldown: 2.1,
    range: 5.5,
    speed: 7.4,
    element: "fire",
    hitDamage: 8,
    magicScale: 0.75,
    hitMagicScale: 0.75,
    areaMagicScale: 0.35,
    areaDamage: 22,
    areaRadius: 1.45,
    explodeOnEnd: true,
    color: "#ffcf5c",
    visuals: {
      castEffect: "cast_fire",
      projectileEffect: "trail_fire",
      impactEffect: "smokey_explosion",
      areaEffect: "burning_ground",
      projectileTexture: "/assets/generated/particles/fireball_trail.png",
      projectileTextureSize: 48,
      rotateProjectileTexture: true,
      projectileTextureRotationOffset: -2.35619449,
    },
    particles: {
      trail: {
        type: "trail_fire",
        size: [3, 7],
        endSize: [1, 3],
        alpha: [0.14, 0.32],
        lifetime: [0.18, 0.38],
        spawnRate: 14,
      },
    },
  },
  ice_bolt: {
    id: "ice_bolt",
    title: "Ice Bolt",
    manaCost: 14,
    cooldown: 1.5,
    range: 6.4,
    speed: 9.4,
    element: "ice",
    hitDamage: 10,
    magicScale: 0.8,
    hitMagicScale: 0.8,
    areaMagicScale: 0.2,
    areaDamage: 4,
    areaRadius: 0.75,
    slowPct: 0.35,
    slowDuration: 2.5,
    color: "#8bdfff",
    visuals: {
      castEffect: "cast_ice",
      projectileEffect: "trail_ice",
      impactEffect: "impact_ice",
      statusEffect: "status_frozen",
    },
  },
  blizzard: {
    id: "blizzard",
    title: "Blizzard",
    castMode: "skyfall",
    manaCost: 34,
    cooldown: 4.4,
    range: 6.8,
    speed: 12.5,
    element: "ice",
    hitDamage: 18,
    magicScale: 1.05,
    hitMagicScale: 1.05,
    areaDamage: 15,
    areaMagicScale: 0.4,
    areaRadius: 1.15,
    dotDamage: 3,
    dotMagicScale: 0.14,
    dotDuration: 3.5,
    slowPct: 0.45,
    slowDuration: 3.4,
    hazardDuration: 2.8,
    hazardMagicScale: 0.14,
    hazardTick: 0.85,
    shardCount: { min: 5, max: 8 },
    shardScatterRadius: 1.65,
    shardFallDistance: 5.2,
    color: "#8bdfff",
    visuals: {
      castEffect: "cast_ice",
      projectileEffect: "trail_ice",
      impactEffect: "impact_ice",
      areaEffect: "frost_ground",
      statusEffect: "status_frozen",
      projectileTexture: "/assets/generated/particles/ice_shard.png",
      projectileTextureSize: 46,
      rotateProjectileTexture: true,
    },
    particles: {
      trail: {
        type: "trail_ice",
        size: [2, 5],
        endSize: [1, 2],
        alpha: [0.16, 0.34],
        lifetime: [0.16, 0.34],
        spawnRate: 15,
      },
    },
  },
  firerain: {
    id: "firerain",
    title: "Fire Rain",
    castMode: "skyfall",
    manaCost: 36,
    cooldown: 4.6,
    range: 6.8,
    speed: 12.2,
    element: "fire",
    hitDamage: 18,
    magicScale: 1.08,
    hitMagicScale: 1.08,
    areaDamage: 22,
    areaMagicScale: 0.5,
    areaRadius: 1.28,
    dotDamage: 6,
    dotMagicScale: 0.18,
    dotDuration: 4.6,
    hazardDuration: 3.4,
    hazardMagicScale: 0.2,
    hazardTick: 0.8,
    shardCount: { min: 5, max: 8 },
    shardScatterRadius: 1.7,
    shardFallDistance: 5.2,
    color: "#ff7b38",
    visuals: {
      castEffect: "cast_fire",
      projectileEffect: "trail_fire",
      impactEffect: "fire_blast",
      areaEffect: "burning_ground",
      statusEffect: "status_burning",
      projectileTexture: "/assets/generated/particles/fireball_trail.png",
      projectileTextureSize: 46,
      rotateProjectileTexture: true,
      projectileTextureRotationOffset: -2.35619449,
    },
    particles: {
      trail: {
        type: "trail_fire",
        size: [2, 5],
        endSize: [1, 2],
        alpha: [0.16, 0.34],
        lifetime: [0.16, 0.34],
        spawnRate: 16,
      },
    },
  },
  energy_beam: {
    id: "energy_beam",
    title: "Energy Beam",
    manaCost: 28,
    cooldown: 3.2,
    range: 7,
    speed: 16,
    element: "arcane",
    hitDamage: 34,
    magicScale: 1.6,
    hitMagicScale: 1.6,
    radius: 0.16,
    color: "#b8a4ff",
    visuals: {
      castEffect: "cast_arcane",
      projectileEffect: null,
      impactEffect: "impact_arcane",
      beam: true,
      beamWidth: 8,
    },
  },
  poison_cloud: {
    id: "poison_cloud",
    title: "Poison Cloud",
    manaCost: 18,
    cooldown: 2.4,
    range: 5.8,
    speed: 7.2,
    element: "poison",
    hitDamage: 4,
    magicScale: 0.35,
    hitMagicScale: 0.35,
    dotDamage: 5,
    dotMagicScale: 0.16,
    dotDuration: 4,
    areaRadius: 0.95,
    hazardDuration: 3.6,
    hazardMagicScale: 0.16,
    hazardTick: 0.65,
    color: "#87d65a",
    visuals: {
      castEffect: "cast_poison",
      projectileEffect: "trail_poison",
      impactEffect: "impact_poison",
      areaEffect: "poison_cloud_lingering",
      statusEffect: "status_poisoned",
    },
  },
  web_slow: {
    id: "web_slow",
    title: "Web Slow",
    manaCost: 0,
    cooldown: 2.8,
    range: 4.6,
    speed: 8,
    element: "nature",
    hitDamage: 3,
    magicScale: 0,
    hitMagicScale: 0,
    areaRadius: 0.6,
    slowPct: 0.45,
    slowDuration: 2.2,
    color: "#d7d4c7",
    visuals: {
      castEffect: "cast_shadow",
      projectileEffect: "trail_shadow",
      impactEffect: "impact_shadow",
      statusEffect: "status_stunned",
    },
  },
};
