export const SUBREGION_CONFIG = {
  cave01_lvl1: {
    id: "cave01_lvl1",
    label: "Gammel grotte",
    kind: "cave",
    generator: "mapRegion",
    mapSize: "small",
    width: 48,
    height: 48,
    persistence: "whileRootRegionActive",
    tileset: [
      { fileName: "tileset/tileset_rock.png", weight: 1, lockedVariant: 2 },
    ],
    objects: [
      // TODO: replace placeholder ruin/stone objects with cave entrance assets when they exist.
      { id: "object_ruin_normal", weight: 1, actionId: "exit_subregion", placementRole: "entryArea", blocking: false },
      { id: "object_pillar_stone", weight: 1, actionId: "enter_cave01_lvl2", placementRole: "farFromEntry", blocking: false },
      { id: "object_stone_cluster", weight: 7 },
      { id: "object_pillar_stone", weight: 2 },
      { id: "object_ruin_normal", weight: 1 },
    ],
    foliageSets: [
      { fileName: "foilage/foilage_boneparts.png", weight: 2 },
      { fileName: "foilage/foilage_plants_mainland.png", weight: 1, scale: 0.7 },
    ],
    mobs: ["Skeleton", "Ghost", { type: "MiniSpider", weight: 2 }],
    npcs: [
      { npcId: "oneleggedman", weight: 1, placementRole: "farFromEntry", actionId: "talk_lost_miner" },
    ],
    foliage: [],
    monsters: [],
    chests: [],
    prefabRules: {},
    spawnCounts: {
      objects: 6,
      foliage: 4,
      decals: 6,
      monsters: { min: 1, max: 2 },
    },
  },

  cave01_lvl2: {
    id: "cave01_lvl2",
    label: "Gammel grotte - dybet",
    kind: "cave",
    generator: "mapRegion",
    mapSize: "small",
    width: 48,
    height: 48,
    persistence: "whileRootRegionActive",
    tileset: [
      { fileName: "tileset/tileset_rock.png", weight: 1, lockedVariant: 3 },
    ],
    objects: [
      // TODO: replace placeholder ruin with cave exit asset when it exists.
      { id: "object_ruin_normal", weight: 1, actionId: "exit_subregion", placementRole: "entryArea", blocking: false },
      { id: "object_stone_cluster", weight: 8 },
      { id: "object_pillar_stone", weight: 3 },
      { id: "object_ruin_normal", weight: 2 },
    ],
    foliageSets: [
      { fileName: "foilage/foilage_boneparts.png", weight: 3 },
    ],
    mobs: ["Skeleton", "Ghost", { type: "Spider", weight: 1.5 }],
    foliage: [],
    monsters: [],
    chests: [],
    prefabRules: {},
    spawnCounts: {
      objects: 5,
      foliage: 3,
      decals: 8,
      monsters: { min: 1, max: 2 },
    },
  },

  inn_crack_cave: {
    id: "inn_crack_cave",
    label: "Hulen under kroen",
    kind: "cave",
    generator: "mapRegion",
    mapSize: "small",
    width: 48,
    height: 48,
    persistence: "whileRootRegionActive",
    tileset: [
      { fileName: "tileset/tileset_rock.png", weight: 1, lockedVariant: 2 },
      { fileName: "tileset/tileset_debriswithblood.png", weight: 1, lockedVariant: 1 },
    ],
    objects: [
      { id: "object_ruin_normal", weight: 1, actionId: "exit_subregion", placementRole: "entryArea", blocking: false },
      { id: "object_stone_cluster", weight: 8 },
      { id: "object_bones", weight: 5, scale: 0.7 },
      { id: "object_pillar_stone", weight: 2 },
    ],
    foliageSets: [
      { fileName: "foilage/foilage_boneparts.png", weight: 4, scale: 0.85 },
      { fileName: "foilage/foilage_deadanimal_small.png", weight: 2, scale: 0.45 },
      { fileName: "foilage/foilage_deadanimal_verysmall.png", weight: 3, scale: 0.3 },
    ],
    decay: [
      { id: "decay_spiderweb", weight: 18 },
      { id: "decay_cracks", weight: 10 },
      { id: "decay_blood", weight: 5 },
      { id: "decay_dust", weight: 8 },
    ],
    mobs: [
      { type: "MiniSpider", weight: 3 },
      { type: "Spider", weight: 3 },
      { type: "MediumSpider", weight: 2 },
      { type: "LargeSpider", weight: 1 },
      { type: "MotherSpider", weight: 0.65 },
    ],
    foliage: [],
    monsters: [],
    chests: [],
    prefabRules: {},
    spawnCounts: {
      objects: 7,
      foliage: 8,
      decals: 12,
      monsters: { min: 12, max: 15 },
    },
    onClear: {
      once: true,
      setFlags: ["inn_crack_cave_cleared"],
      addCounters: {
        subregionsCleared: 1,
      },
      message: "Hulen er ryddet. Revnen kan nu oedelaegges.",
      questStepComplete: {
        questId: "check_inn_infestation",
        stepId: "clear_crack_cave",
      },
    },
  },

  blacksmith_boar_cave_lvl1: {
    id: "blacksmith_boar_cave_lvl1",
    label: "Blodsporet i grotten",
    kind: "cave",
    generator: "mapRegion",
    mapSize: "small",
    width: 52,
    height: 52,
    persistence: "whileRootRegionActive",
    tileset: [
      { fileName: "tileset/tileset_rock.png", weight: 1, lockedVariant: 2 },
    ],
    objects: [
      { id: "object_caves", weight: 1, actionId: "exit_subregion", placementRole: "entryArea", blocking: false },
      { id: "object_stone_cluster", weight: 4 },
      { id: "object_bones", weight: 2, scale: 0.7 },
    ],
    foliageSets: [
      { fileName: "foilage/foilage_plants_mainland.png", weight: 7, scale: 0.75 },
      { fileName: "foilage/foilage_roots.png", weight: 4, scale: 0.7 },
      { fileName: "foilage/foilage_boneparts.png", weight: 2, scale: 0.7 },
    ],
    decay: [
      { id: "decay_blood", weight: 14 },
      { id: "decay_spiderweb", weight: 18 },
      { id: "decay_dust", weight: 8 },
    ],
    mobs: [
      { type: "Spider", weight: 4 },
      { type: "MediumSpider", weight: 3 },
      { type: "LargeSpider", weight: 1 },
    ],
    foliage: [
      { fileName: "object/object_cracks02.png", weight: 1, actionId: "enter_blacksmith_boar_cave_lvl2", placementRole: "farFromEntry", radius: 0.65, variant: 6, scale: 1.8, depthMode: "ground", sortAnchor: { x: 0.5, y: 1 } },
    ],
    monsters: [],
    chests: [],
    prefabRules: {},
    spawnCounts: {
      objects: 6,
      foliage: 18,
      decals: 18,
      monsters: { min: 18, max: 23 },
    },
  },

  blacksmith_boar_cave_lvl2: {
    id: "blacksmith_boar_cave_lvl2",
    label: "Den dybere revne",
    kind: "cave",
    generator: "mapRegion",
    mapSize: "small",
    width: 54,
    height: 54,
    persistence: "whileRootRegionActive",
    tileset: [
      { fileName: "tileset/tileset_rock.png", weight: 1, lockedVariant: 3 },
    ],
    objects: [
      { id: "object_caves", weight: 1, actionId: "enter_blacksmith_boar_cave_lvl3", placementRole: "farFromEntry", blocking: false },
      { id: "object_stone_cluster", weight: 10 },
      { id: "object_pillar_stone", weight: 3 },
      { id: "object_bones", weight: 1, scale: 0.65 },
    ],
    foliageSets: [
      { fileName: "foilage/foilage_boneparts.png", weight: 2, scale: 0.7 },
      { fileName: "foilage/foilage_plants_stone.png", weight: 1, scale: 0.55 },
    ],
    decay: [
      { id: "decay_blood", weight: 12 },
      { id: "decay_spiderweb", weight: 14 },
      { id: "decay_dust", weight: 12 },
    ],
    mobs: [
      { type: "MiniSpider", weight: 7 },
      { type: "Spider", weight: 2 },
      { type: "MediumSpider", weight: 1 },
    ],
    foliage: [
      { fileName: "object/object_cracks02.png", weight: 1, actionId: "exit_subregion", placementRole: "entryArea", radius: 0.65, variant: 1, scale: 1.8, depthMode: "ground", sortAnchor: { x: 0.5, y: 1 } },
    ],
    monsters: [],
    chests: [],
    prefabRules: {},
    spawnCounts: {
      objects: 11,
      foliage: 5,
      decals: 20,
      monsters: { min: 20, max: 26 },
    },
  },

  blacksmith_boar_cave_lvl3: {
    id: "blacksmith_boar_cave_lvl3",
    label: "Vildsvinets hule",
    kind: "cave",
    generator: "mapRegion",
    mapSize: "small",
    width: 56,
    height: 56,
    persistence: "whileRootRegionActive",
    tileset: [
      { fileName: "tileset/tileset_rock.png", weight: 1, lockedVariant: 3 },
      { fileName: "tileset/tileset_debriswithblood.png", weight: 1, lockedVariant: 1 },
    ],
    objects: [
      { id: "object_caves", weight: 1, actionId: "exit_subregion", placementRole: "entryArea", blocking: false },
      { id: "object_stone_cluster", weight: 2 },
      { id: "object_bones", weight: 1, scale: 0.7 },
    ],
    foliageSets: [
      { fileName: "foilage/foilage_boneparts.png", weight: 1, scale: 0.65 },
      { fileName: "foilage/foilage_plants_stone.png", weight: 1, scale: 0.45 },
    ],
    decay: [
      { id: "decay_blood", weight: 18 },
      { id: "decay_dust", weight: 8 },
    ],
    mobs: [
      { type: "Wild Boar", weight: 5 },
      { type: "Blacksmiths Bane", weight: 0.5 },
    ],
    foliage: [],
    monsters: [],
    chests: [],
    prefabRules: {},
    spawnCounts: {
      objects: 3,
      foliage: 3,
      decals: 18,
      monsters: { min: 13, max: 17 },
    },
  },

  the_mine_lvl1: {
    id: "the_mine_lvl1",
    label: "Den gamle mine",
    kind: "mine",
    generator: "mapRegion",
    mapSize: "small",
    width: 52,
    height: 52,
    persistence: "whileRootRegionActive",
    tileset: [
      { fileName: "tileset/tileset_rock.png", weight: 1, lockedVariant: 2 },
    ],
    objects: [
      { id: "object_well", weight: 1, actionId: "exit_subregion", placementRole: "entryArea", blocking: false },
      { id: "object_caves", weight: 1, actionId: "enter_the_mine_lvl2", placementRole: "farFromEntry", blocking: false },
      { id: "object_stone_cluster", weight: 12 },
      { id: "object_pillar_stone", weight: 3 },
      { id: "object_bones", weight: 1, scale: 0.65 },
    ],
    foliageSets: [
      { fileName: "foilage/foilage_boneparts.png", weight: 2, scale: 0.65 },
      { fileName: "foilage/foilage_plants_stone.png", weight: 1, scale: 0.55 },
    ],
    decay: [
      { id: "decay_dust", weight: 14 },
      { id: "decay_cracks", weight: 10 },
      { id: "decay_spiderweb", weight: 6 },
    ],
    mobs: [
      { type: "MiniSpider", weight: 4 },
      { type: "Spider", weight: 2 },
      { type: "Skeleton", weight: 1 },
    ],
    foliage: [],
    monsters: [],
    chests: [],
    prefabRules: {},
    spawnCounts: {
      objects: 14,
      foliage: 5,
      decals: 18,
      monsters: { min: 14, max: 18 },
    },
    onClear: {
      once: true,
      conditions: { questActive: "veldor_clear_the_mine" },
      setFlags: ["the_mine_lvl1_cleared"],
      addCounters: { subregionsCleared: 1 },
      message: "Foerste mineniveau er ryddet.",
    },
  },

  the_mine_lvl2: {
    id: "the_mine_lvl2",
    label: "Den gamle mine - dybere skakt",
    kind: "mine",
    generator: "mapRegion",
    mapSize: "small",
    width: 54,
    height: 54,
    persistence: "whileRootRegionActive",
    tileset: [
      { fileName: "tileset/tileset_rock.png", weight: 1, lockedVariant: 3 },
    ],
    objects: [
      { id: "object_caves", weight: 1, actionId: "exit_subregion", placementRole: "entryArea", blocking: false },
      { id: "object_caves", weight: 1, actionId: "enter_the_mine_lvl3", placementRole: "farFromEntry", blocking: false },
      { id: "object_stone_cluster", weight: 14 },
      { id: "object_pillar_stone", weight: 4 },
      { id: "object_bones", weight: 2, scale: 0.65 },
    ],
    foliageSets: [
      { fileName: "foilage/foilage_boneparts.png", weight: 3, scale: 0.65 },
      { fileName: "foilage/foilage_plants_stone.png", weight: 1, scale: 0.55 },
    ],
    decay: [
      { id: "decay_dust", weight: 14 },
      { id: "decay_cracks", weight: 12 },
      { id: "decay_spiderweb", weight: 8 },
    ],
    mobs: [
      { type: "Spider", weight: 4 },
      { type: "MediumSpider", weight: 2 },
      { type: "Skeleton", weight: 1 },
      { type: "Ghost", weight: 0.5 },
    ],
    foliage: [],
    monsters: [],
    chests: [],
    prefabRules: {},
    spawnCounts: {
      objects: 16,
      foliage: 5,
      decals: 20,
      monsters: { min: 17, max: 22 },
    },
    onClear: {
      once: true,
      conditions: { questActive: "veldor_clear_the_mine" },
      setFlags: ["the_mine_lvl2_cleared"],
      addCounters: { subregionsCleared: 1 },
      message: "Andet mineniveau er ryddet.",
    },
  },

  the_mine_lvl3: {
    id: "the_mine_lvl3",
    label: "Den gamle mine - bundskakten",
    kind: "mine",
    generator: "mapRegion",
    mapSize: "small",
    width: 56,
    height: 56,
    persistence: "whileRootRegionActive",
    tileset: [
      { fileName: "tileset/tileset_rock.png", weight: 1, lockedVariant: 3 },
      { fileName: "tileset/tileset_debriswithblood.png", weight: 1, lockedVariant: 1 },
    ],
    objects: [
      { id: "object_caves", weight: 1, actionId: "exit_subregion", placementRole: "entryArea", blocking: false },
      { id: "object_stone_cluster", weight: 16 },
      { id: "object_pillar_stone", weight: 4 },
      { id: "object_bones", weight: 3, scale: 0.7 },
    ],
    foliageSets: [
      { fileName: "foilage/foilage_boneparts.png", weight: 4, scale: 0.7 },
      { fileName: "foilage/foilage_plants_stone.png", weight: 1, scale: 0.5 },
    ],
    decay: [
      { id: "decay_dust", weight: 12 },
      { id: "decay_cracks", weight: 14 },
      { id: "decay_blood", weight: 5 },
      { id: "decay_spiderweb", weight: 8 },
    ],
    mobs: [
      { type: "MediumSpider", weight: 3 },
      { type: "LargeSpider", weight: 1.4 },
      { type: "Skeleton", weight: 2 },
      { type: "Ghost", weight: 0.7 },
    ],
    npcs: [
      { npcId: "poorminer", weight: 1, placementRole: "farFromEntry", conditions: { questActive: "miri_find_father" } },
      {
        npcId: "poorminer",
        weight: 1,
        placementRole: "entryArea",
        conditions: {
          all: [
            { questCompleted: "miri_find_father" },
            { not: { questCompleted: "rusk_gold_nuggets" } },
          ],
        },
      },
    ],
    foliage: [],
    monsters: [],
    chests: [],
    prefabRules: {},
    spawnCounts: {
      objects: 17,
      foliage: 5,
      decals: 22,
      monsters: { min: 19, max: 24 },
    },
    onClear: {
      once: true,
      conditions: { questActive: "veldor_clear_the_mine" },
      setFlags: ["the_mine_lvl3_cleared"],
      addCounters: { subregionsCleared: 1 },
      message: "Bundskakten er ryddet.",
    },
  },

  forest_mine_lvl1: {
    id: "forest_mine_lvl1",
    label: "Skovminen",
    kind: "mine",
    generator: "mapRegion",
    mapSize: "small",
    width: 52,
    height: 52,
    persistence: "whileRootRegionActive",
    tileset: [
      { fileName: "tileset/tileset_rock.png", weight: 1, lockedVariant: 2 },
    ],
    objects: [
      { id: "object_caves", weight: 1, actionId: "exit_subregion", placementRole: "entryArea", blocking: false },
      { id: "object_caves", weight: 1, actionId: "enter_forest_mine_lvl2", placementRole: "farFromEntry", blocking: false },
      { id: "object_stone_cluster", weight: 8 },
      { id: "object_bones", weight: 2, scale: 0.65 },
    ],
    foliageSets: [
      { fileName: "foilage/foilage_roots.png", weight: 4, scale: 0.7 },
      { fileName: "foilage/foilage_boneparts.png", weight: 2, scale: 0.65 },
    ],
    decay: [
      { id: "decay_dust", weight: 10 },
      { id: "decay_cracks", weight: 8 },
      { id: "decay_spiderweb", weight: 8 },
    ],
    mobs: [
      { type: "Spider", weight: 3 },
      { type: "Skeleton", weight: 2 },
      { type: "Ghost", weight: 0.7 },
    ],
    foliage: [],
    monsters: [],
    chests: [],
    prefabRules: {},
    spawnCounts: {
      objects: 11,
      foliage: 9,
      decals: 16,
      monsters: { min: 13, max: 17 },
    },
  },

  forest_mine_lvl2: {
    id: "forest_mine_lvl2",
    label: "Skovminen - rodskakten",
    kind: "mine",
    generator: "mapRegion",
    mapSize: "small",
    width: 54,
    height: 54,
    persistence: "whileRootRegionActive",
    tileset: [
      { fileName: "tileset/tileset_rock.png", weight: 1, lockedVariant: 3 },
    ],
    objects: [
      { id: "object_caves", weight: 1, actionId: "exit_subregion", placementRole: "entryArea", blocking: false },
      { id: "object_caves", weight: 1, actionId: "enter_forest_mine_lvl3", placementRole: "farFromEntry", blocking: false },
      { id: "object_stone_cluster", weight: 9 },
      { id: "object_bones", weight: 3, scale: 0.65 },
    ],
    foliageSets: [
      { fileName: "foilage/foilage_roots.png", weight: 5, scale: 0.7 },
      { fileName: "foilage/foilage_boneparts.png", weight: 3, scale: 0.65 },
    ],
    decay: [
      { id: "decay_dust", weight: 10 },
      { id: "decay_cracks", weight: 10 },
      { id: "decay_blood", weight: 3 },
      { id: "decay_spiderweb", weight: 10 },
    ],
    mobs: [
      { type: "MediumSpider", weight: 3 },
      { type: "Skeleton", weight: 2 },
      { type: "Ghost", weight: 1 },
    ],
    foliage: [],
    monsters: [],
    chests: [],
    prefabRules: {},
    spawnCounts: {
      objects: 12,
      foliage: 10,
      decals: 18,
      monsters: { min: 16, max: 21 },
    },
  },

  forest_mine_lvl3: {
    id: "forest_mine_lvl3",
    label: "Skovminen - den lukkede grav",
    kind: "mine",
    generator: "mapRegion",
    mapSize: "small",
    width: 56,
    height: 56,
    persistence: "whileRootRegionActive",
    tileset: [
      { fileName: "tileset/tileset_rock.png", weight: 1, lockedVariant: 3 },
      { fileName: "tileset/tileset_debriswithblood.png", weight: 1, lockedVariant: 1 },
    ],
    objects: [
      { id: "object_caves", weight: 1, actionId: "exit_subregion", placementRole: "entryArea", blocking: false },
      { id: "object_stone_cluster", weight: 10 },
      { id: "object_bones", weight: 4, scale: 0.7 },
    ],
    foliageSets: [
      { fileName: "foilage/foilage_roots.png", weight: 5, scale: 0.7 },
      { fileName: "foilage/foilage_boneparts.png", weight: 5, scale: 0.7 },
    ],
    foliage: [
      {
        fileName: "foilage/foilage_deadvillages.png",
        weight: 1,
        placementRole: "farFromEntry",
        scale: 1.35,
        cell: 10,
        actionId: "inspect_veldors_wife_corpse",
        questTargetKey: "veldors_wife_corpse",
        conditions: { questActive: "find_veldors_wife", notFlag: "veldors_wife_found" },
      },
    ],
    decay: [
      { id: "decay_dust", weight: 8 },
      { id: "decay_cracks", weight: 12 },
      { id: "decay_blood", weight: 10 },
      { id: "decay_spiderweb", weight: 12 },
    ],
    mobs: [
      { type: "LargeSpider", weight: 2 },
      { type: "Skeleton", weight: 2 },
      { type: "Ghost", weight: 1.2 },
    ],
    monsters: [],
    chests: [],
    prefabRules: {},
    spawnCounts: {
      objects: 12,
      foliage: 8,
      decals: 22,
      monsters: { min: 18, max: 23 },
    },
  },
};
