export {
  CITY_STORAGE_KEY,
  SAVE_INDEX_STORAGE_KEY,
  SAVE_SLOT_STORAGE_PREFIX,
  CITY_SLOT_STORAGE_PREFIX,
  REGION_CORRUPTION_SLOT_STORAGE_PREFIX,
  REGION_MAP_LAST_SLOT_STORAGE_PREFIX,
  REGION_CORRUPTION_STORAGE_KEY,
  REGION_MAP_LAST_ID_STORAGE_KEY,
  regionStatusKey,
  saveSlotKeys,
} from "../../storage/saveKeys.js";
