import { normalizeSkillTree } from "../game/config/skill-tree-config.js";
import {
  CITY_STORAGE_KEY,
  regionStatusKey,
} from "./save/save-keys.js";
import {
  collectSaveSlots,
  createSaveSlot,
  loadRegionCorruption,
  loadRegionMapInitialId,
  normalizeSaveSlot,
  saveRegionCorruption,
  upsertSaveSlot,
} from "./save/save-slots.js";
import {
  INVENTORY_FILTERS,
  isItemRequiredByActiveQuests,
  itemMatchesInventoryFilter,
} from "./inventory/inventory-filters.js";
import { InventoryItemDetail } from "./inventory/inventory-item-detail.jsx";
import { MergeChoiceDialog } from "./inventory/merge-choice-dialog.jsx";
import { ReadableDialog } from "./inventory/readable-dialog.jsx";
import {
  QuestDetailDialog,
  QuestObjectiveMeta,
  QuestOfferDialog,
  QuestOverviewDialog,
} from "./quests/quest-dialogs.jsx";
import {
  MinimapDialog,
  RegionMapDialog,
  mapRegionColor,
} from "./map/map-dialogs.jsx";
import { HeroDialog } from "./hero/hero-dialog.jsx";
import {
  AtlasIcon,
  ImageIcon,
  InventoryIcon,
  ITEM_GOLD_ICON_URL,
  ITEM_MONEY_ICON_URL,
  ITEM_STANDARD_ICON_URL,
  QUICKBAR_ATTACK_ICON_URL,
  QUICKBAR_CITY_ICON_URL,
  QUICKBAR_HEALTH_POTION_ICON_URL,
  QUICKBAR_MANA_POTION_ICON_URL,
  QUICKBAR_QUEST_ICON_URL,
  QUICKBAR_WILDERNESS_ICON_URL,
} from "./ui/icons.jsx";
import { StartMenu } from "./ui/start-menu.jsx";
import {
  CITY_CITIZEN_CONDITION_DEFS,
  CITY_STAT_ALIASES,
  CITY_STAT_DEFS,
  CITY_STAT_ICON_URLS,
  CityCitizenConditions,
  CityStatsTopBar,
  ResourceBar,
} from "./hud/resource-bar.jsx";
const emptySnapshot = {
  player: {
    level: 1,
    hp: 1,
    maxHp: 1,
    mana: 1,
    maxMana: 1,
    xp: 0,
    nextXp: 1,
    gold: 0,
    popularity: 0,
    damage: "0-0",
    armor: 0,
    mode: "melee",
    skillTree: normalizeSkillTree(),
    skillPoints: 0,
    unlockedSpells: ["ember_spark"],
    activeSpellId: "ember_spark",
    activeSpellTitle: "Ember Spark",
    critChance: 0,
    critDamage: 1.5,
    blockChance: 0,
    dodgeChance: 0,
    lifeSteal: 0,
    magicFind: 0,
    goldFind: 0,
    resourceFind: 0,
    xpGain: 0,
  },
  zone: { name: "Stonewake Wilds", level: 1, seed: 7341 },
  region: { name: "Stonewake Wilds", index: 1, seed: 7341 },
  regionRun: null,
  mapReturn: null,
  lastDeath: null,
  mobs: { total: 0, alive: 0, killed: 0 },
  exitPrompt: false,
  nearbyFoliageLoot: null,
  inventory: [],
  equipment: [],
  hoverMonster: null,
  quickActions: { healthPotions: 0, manaPotions: 0, potionCooldown: 0 },
  quests: { active: [], completed: [], cityFade: [], wildernessNpc: null, nearbyQuestgiver: null },
  toasts: [],
};

const CITY_BUILDING_CHIPS_ALWAYS_VISIBLE = true;
export {
  InventoryItemDetail,
  collectSaveSlots,
  createSaveSlot,
  upsertSaveSlot,
  normalizeSaveSlot,
  saveRegionCorruption,
  loadRegionMapInitialId,
  loadRegionCorruption,
  regionStatusKey,
  mapRegionColor,
  emptySnapshot,
  CITY_BUILDING_CHIPS_ALWAYS_VISIBLE,
  CITY_STORAGE_KEY,
  StartMenu,
  ResourceBar,
  CityStatsTopBar,
  CityCitizenConditions,
  MergeChoiceDialog,
  ReadableDialog,
  QuestObjectiveMeta,
  QuestOfferDialog,
  QuestDetailDialog,
  QuestOverviewDialog,
  MinimapDialog,
  RegionMapDialog,
  HeroDialog,
  ImageIcon,
  AtlasIcon,
  InventoryIcon,
  itemMatchesInventoryFilter,
  isItemRequiredByActiveQuests,
  INVENTORY_FILTERS,
  QUICKBAR_HEALTH_POTION_ICON_URL,
  QUICKBAR_MANA_POTION_ICON_URL,
  QUICKBAR_ATTACK_ICON_URL,
  QUICKBAR_CITY_ICON_URL,
  QUICKBAR_WILDERNESS_ICON_URL,
  QUICKBAR_QUEST_ICON_URL,
  ITEM_STANDARD_ICON_URL,
  ITEM_GOLD_ICON_URL,
  ITEM_MONEY_ICON_URL,
  CITY_STAT_DEFS,
  CITY_STAT_ALIASES,
  CITY_STAT_ICON_URLS,
  CITY_CITIZEN_CONDITION_DEFS
};
